package com.sda.mobile.ui.viewmodel

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.sda.mobile.auth.AuthenticatorLinker
import com.sda.mobile.auth.LoginClient
import com.sda.mobile.model.AuthGuardType
import com.sda.mobile.model.SessionData
import com.sda.mobile.model.SteamGuardAccount
import com.sda.mobile.network.TimeAligner
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

/** Mirrors LoginType in the desktop app's LoginWindow.axaml.cs. */
enum class LoginPurpose { INITIAL, REFRESH, IMPORT }

enum class LoginPhase {
    CREDENTIALS, GUARD_CODE, LINK_CONFIRM, PHONE_NUMBER, PHONE_EMAIL_WAIT, PHONE_SMS, LINK_SMS, DONE, ERROR
}

data class LoginUiState(
    val phase: LoginPhase = LoginPhase.CREDENTIALS,
    val busy: Boolean = false,
    val error: String? = null,
    val guardType: AuthGuardType? = null,
    val guardMessage: String? = null,
    val confirmationEmail: String? = null,
    val resultAccount: SteamGuardAccount? = null,
    val resultSession: SessionData? = null
)

/**
 * Drives the full login -> (guard code) -> [INITIAL only: confirm -> add authenticator ->
 * (phone linking if needed) -> finalize SMS code] wizard. This is a Kotlin port of the state
 * machine spread across LoginWindow.axaml.cs + AuthenticatorLinker.cs on desktop, adapted for
 * this app's HTTP-only LoginClient (see auth/LoginClient.kt for why).
 */
class LoginViewModel(
    application: Application,
    private val purpose: LoginPurpose,
    private val existingAccount: SteamGuardAccount?
) : AndroidViewModel(application) {

    private val loginClient = LoginClient()
    private var linker: AuthenticatorLinker? = null

    private val _state = MutableStateFlow(LoginUiState())
    val state: StateFlow<LoginUiState> = _state.asStateFlow()

    /** If we already hold this account (Refresh/Import) and Steam asks for a DEVICE_CODE
     * (TOTP), we can generate it locally instead of prompting - matches AvaloniaAuthenticator
     * .GetDeviceCodeAsync on desktop. Returns null if we don't have the shared_secret. */
    fun tryAutoGenerateDeviceCode(): String? {
        val secret = existingAccount?.sharedSecret ?: return null
        return com.sda.mobile.crypto.SteamGuardCodeGenerator.generateCode(secret, TimeAligner.getSteamTimeCached())
    }

    fun submitCredentials(username: String, password: String) {
        _state.update { it.copy(busy = true, error = null) }
        viewModelScope.launch {
            try {
                TimeAligner.alignIfNeeded()
                handleStep(loginClient.beginLogin(username, password))
            } catch (e: Exception) {
                _state.update { it.copy(busy = false, phase = LoginPhase.ERROR, error = "Steam login failed: ${e.message}") }
            }
        }
    }

    fun submitGuardCode(code: String) {
        _state.update { it.copy(busy = true, error = null) }
        viewModelScope.launch {
            try {
                handleStep(loginClient.submitGuardCode(code, _state.value.guardType ?: AuthGuardType.EMAIL_CODE))
            } catch (e: Exception) {
                _state.update { it.copy(busy = false, error = "That code was rejected: ${e.message}") }
            }
        }
    }

    private suspend fun handleStep(step: LoginClient.LoginStep) {
        when (step) {
            is LoginClient.LoginStep.NeedsGuardCode ->
                _state.update { it.copy(busy = false, phase = LoginPhase.GUARD_CODE, guardType = step.guardType, guardMessage = step.associatedMessage) }
            is LoginClient.LoginStep.Success -> onLoginSucceeded(step.session)
            is LoginClient.LoginStep.Failed ->
                _state.update { it.copy(busy = false, phase = LoginPhase.ERROR, error = step.reason) }
        }
    }

    private fun onLoginSucceeded(session: SessionData) {
        when (purpose) {
            LoginPurpose.REFRESH, LoginPurpose.IMPORT ->
                _state.update { it.copy(busy = false, phase = LoginPhase.DONE, resultSession = session) }
            LoginPurpose.INITIAL -> {
                linker = AuthenticatorLinker(session)
                _state.update { it.copy(busy = false, phase = LoginPhase.LINK_CONFIRM, resultSession = session) }
            }
        }
    }

    /** User tapped "yes, add SDA Mobile as my authenticator" on the LINK_CONFIRM screen. */
    fun confirmProceedWithLink() {
        _state.update { it.copy(busy = true, error = null) }
        viewModelScope.launch { runAddAuthenticatorStep() }
    }

    private suspend fun runAddAuthenticatorStep() {
        val l = linker ?: return
        when (l.addAuthenticator()) {
            AuthenticatorLinker.LinkResult.MUST_PROVIDE_PHONE_NUMBER ->
                _state.update { it.copy(busy = false, phase = LoginPhase.PHONE_NUMBER) }
            AuthenticatorLinker.LinkResult.AUTHENTICATOR_PRESENT ->
                _state.update { it.copy(busy = false, phase = LoginPhase.ERROR, error = "This account already has an authenticator. Remove it from the account before adding a new one.") }
            AuthenticatorLinker.LinkResult.GENERAL_FAILURE ->
                _state.update { it.copy(busy = false, phase = LoginPhase.ERROR, error = "Steam refused to add an authenticator to this account.") }
            AuthenticatorLinker.LinkResult.AWAITING_FINALIZATION ->
                _state.update { it.copy(busy = false, phase = LoginPhase.LINK_SMS, resultAccount = l.linkedAccount) }
        }
    }

    fun submitPhoneNumber(phoneNumber: String, countryCode: String?) {
        _state.update { it.copy(busy = true, error = null) }
        viewModelScope.launch {
            val l = linker ?: return@launch
            when (l.addPhoneNumber(phoneNumber, countryCode, null)) {
                AuthenticatorLinker.PhoneLinkResult.MUST_CONFIRM_EMAIL ->
                    _state.update { it.copy(busy = false, phase = LoginPhase.PHONE_EMAIL_WAIT, confirmationEmail = l.confirmationEmailAddress) }
                AuthenticatorLinker.PhoneLinkResult.PHONE_ADDED -> runAddAuthenticatorStep()
                else -> _state.update { it.copy(busy = false, error = "Could not set that phone number - double check the format and try again.") }
            }
        }
    }

    /** Call when the user taps "I clicked the email link" on the PHONE_EMAIL_WAIT screen. */
    fun checkEmailConfirmed() {
        _state.update { it.copy(busy = true, error = null) }
        viewModelScope.launch {
            val l = linker ?: return@launch
            when (l.addPhoneNumber(null, null, null)) {
                AuthenticatorLinker.PhoneLinkResult.MUST_CONFIRM_EMAIL ->
                    _state.update { it.copy(busy = false, error = "Still waiting - click the confirmation link in your email first.") }
                AuthenticatorLinker.PhoneLinkResult.MUST_CONFIRM_SMS ->
                    _state.update { it.copy(busy = false, phase = LoginPhase.PHONE_SMS) }
                AuthenticatorLinker.PhoneLinkResult.PHONE_ADDED -> runAddAuthenticatorStep()
                else -> _state.update { it.copy(busy = false, error = "Something went wrong confirming your phone number.") }
            }
        }
    }

    fun submitPhoneSmsCode(code: String) {
        _state.update { it.copy(busy = true, error = null) }
        viewModelScope.launch {
            val l = linker ?: return@launch
            when (l.addPhoneNumber(null, null, code)) {
                AuthenticatorLinker.PhoneLinkResult.PHONE_ADDED -> runAddAuthenticatorStep()
                else -> _state.update { it.copy(busy = false, error = "That code was rejected, try again.") }
            }
        }
    }

    /** Final step: the SMS Steam sent right after AddAuthenticator succeeded. */
    fun submitFinalizeSmsCode(code: String) {
        _state.update { it.copy(busy = true, error = null) }
        viewModelScope.launch {
            val l = linker ?: return@launch
            when (l.finalizeAddAuthenticator(code)) {
                AuthenticatorLinker.FinalizeResult.SUCCESS ->
                    _state.update { it.copy(busy = false, phase = LoginPhase.DONE, resultAccount = l.linkedAccount) }
                AuthenticatorLinker.FinalizeResult.BAD_SMS_CODE ->
                    _state.update { it.copy(busy = false, error = "That SMS code was rejected. Try again.") }
                AuthenticatorLinker.FinalizeResult.UNABLE_TO_GENERATE_CORRECT_CODES ->
                    _state.update { it.copy(busy = false, phase = LoginPhase.ERROR, error = "Couldn't generate a matching code in time - this can happen with a skewed device clock. Please retry.") }
                AuthenticatorLinker.FinalizeResult.GENERAL_FAILURE ->
                    _state.update { it.copy(busy = false, phase = LoginPhase.ERROR, error = "Failed to finalize the authenticator.") }
            }
        }
    }

    class Factory(
        private val application: Application,
        private val purpose: LoginPurpose,
        private val existingAccount: SteamGuardAccount?
    ) : ViewModelProvider.Factory {
        @Suppress("UNCHECKED_CAST")
        override fun <T : ViewModel> create(modelClass: Class<T>): T =
            LoginViewModel(application, purpose, existingAccount) as T
    }
}
